### ISSUE TITLE
C# Wrapper

### ISSUE THREAD

**Issue by shauleiz** [shauleiz/vGen#3]

**Comment by Axadiw** [comment]
I've ported couple of the APIs from vGen to C# in my project.

Feel free to check it here: https://github.com/Axadiw/MFIGamepadFeeder/blob/master/vGenWrapper/vGenWrapper.cs

Maybe it would help you to create full C# wrapper :)

**Comment by shauleiz** [comment]
@Axadiw - I will probably use it. Thank you.

**Comment by shauleiz** [comment]
Added in v1.0.0.15
