### ISSUE TITLE
vGenWrapper: Calling SetDevAxis on a vXbox pad right after Acquire does not move axis

### ISSUE THREAD

**Issue by evilC** [shauleiz/vGen#5]
As the title says, there is a period of time between Acquiring an xbox device (Causing it to be plugged in) and it responding to input.  
Furthermore, if, during this time you set the axis to say 50, then trying to set it to 50 again after a number of seconds does not fix this.

**Comment by shauleiz** [comment]
> there is a period of time between Acquiring an xbox device (Causing it to be plugged in) and it responding to input.

True. You can check if it is ready by calling method isControllerPluggedIn().

> during this time you set the axis to say 50, then trying to set it to 50 again after a number of seconds does not fix this.

Strange. I don't think that there's a check for duplication. Did you try another value, say 49?

**Comment by evilC** [comment]
`isControllerPluggedIn()` seemed to return true regardless of whether it was ready yet or not.  
I will double-check tonight to make sure.  

Yes, I tried another value, which worked fine.

**Comment by shauleiz** [comment]
We have two problems here:

1.  The unreliability of isControllerPluggedIn() which may be overcome with adding a little delay.
2.  The fact that you cannot write '50' to the axis.

Well, taking a look at the manual I found the Axis value Range: (-32768 to 32767 ). So when you write 50 it is internally rounded up to 0.
I tested with 10000 and it was OK.

**Comment by evilC** [comment]
This is using the C# wrapper for vGen.  
Axes are 0..100 floating point.  
Even if it were integers in the range -32768...32768 though, I fail to see why writing 50 would not work - this is still within the range.

**Comment by shauleiz** [comment]
It is within the rage but round down to zero.

**Comment by evilC** [comment]
Oh, I see, sorry :)  
When I did the test, I used 100, I just wrote 50 in this bug report.

**Comment by shauleiz** [comment]
Try 10000 and you'll see a proper reaction. This is what I did.

**Comment by evilC** [comment]
10000 is an invalid value.  
Actually, I think I was right the first time and you misunderstood - Surely 100 does not map to 0, it maps to 32767?  
ie in a scale 0..100, then 100 cannot map to the mid-point, it must map to one of the extremes.

**Comment by shauleiz** [comment]
I think I am wasting your time. Please create a sample project that exemplifies the problem and send it over to me to see.  Perhaps I will finally understand.

**Comment by evilC** [comment]
OK, something odd seems to be going on...  

Here is the sample code:  

```
    class Program
    {
        static void Main(string[] args)
        {
            var vGenWrapper = new vGenInterfaceWrap.vGen();
            int hDev = 0;
            vGenWrapper.AcquireDev(1, DevType.vXbox, ref hDev);
            Thread.Sleep(5000);
            vGenWrapper.SetDevAxis(hDev, 1, 100);
            Console.ReadLine();
            vGenWrapper.RelinquishDev(hDev);
        }
    }
```

What I have noticed is that if, during the 5 second sleep, I open joy.cpl and view the XBox controller, then the preview **does** show it moving to 100%.  
However, if I wait for `SetDevAxis` to be called and **then** open joy.cpl for the Xbox controller, it **does not** show the axis as being at 100%.  
So I am not sure what is wrong - vJoy could be behaving perfectly well, it could just be windows giving me bad information.

**Comment by evilC** [comment]
Let me make that clearer:  
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace BasicTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var vGenWrapper = new vGenInterfaceWrap.vGen();
            int hDev = 0;
            vGenWrapper.AcquireDev(1, DevType.vXbox, ref hDev);
            Console.WriteLine("Device Acquired, press ENTER to set axis");
            Console.ReadLine();
            vGenWrapper.SetDevAxis(hDev, 1, 100);
            Console.WriteLine("Axis set, press ENTER to relinquish");
            Console.ReadLine();
            vGenWrapper.RelinquishDev(hDev);
        }
    }
}
```
Test 1 (Good):
1) Run app, wait for it to acquire axis  
2) In joy.cpl, open preview for Xbox controller  
3) Hit Enter in console app to set axis  
4) In joy.cpl preview, axis moves  

Test 2 (Bad):
1) Run app, wait for it to acquire axis  
2) Hit Enter in console app to set axis  
3) In joy.cpl, open preview for Xbox controller  
4) In joy.cpl preview, the axis is still at center  

So, not sure it is vJoy at all, it seems like maybe windows is giving me bad info or something? Can't tell for 100% sure what the actual state of the xbox pad is.

**Comment by evilC** [comment]
It turns out that this is not a vJoy bug, sorry to waste your time.  
Use [HTML5 Gamepad Tester](http://html5gamepad.com/) to view stick state instead of joy.cpl, and there is clearly no problem.  
It appears that any updates sent to the Vxbox controller **before** you open the joy.cpl preview window are not shown when you open the window.  
HTML5 Gamepad tester correctly shows that the axis has indeed been correctly set though.

**Comment by shauleiz** [comment]
No problem. JOY.CPL is indeed unreliable.
For vJoy I use the Monitor that is part of the package.
For Xbox controller I use SCPUser that is part of the old SCP project if you don't have it I'll post it for you

**Comment by evilC** [comment]
If there is an SCPVBus equivalent of the monitor, then yeah. Would it not be a good idea to package it with the vJoy download?

**Comment by shauleiz** [comment]
It is not that user friendly  - please let me know what you think.
https://www.dropbox.com/s/2f3xzj4zz1tns8p/SCPUser.exe?dl=0
